
version: '3.7'

services:
  web:
    build: ./
    command: >
      sh -c "python3 manage.py migrate
      && python3 manage.py loaddata dhmigration/fixtures/initial_data.json
      && python3 manage.py declare_procedure
      && gunicorn datahub.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/datahub
      - static:/datahub/static
      - media:/datahub/media
    ports:
      - 8000:8000
    environment:
      - HOST=db
      - DB_NAME=datahub
      - DB_USER=postgres
      - DB_PASS=dhub1112
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=datahub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dhub1112
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  nginx:
    build: ./nginx
    volumes:
      - media:/datahub/media
      - static:/datahub/static
    ports:
      - "1300:80"
    depends_on:
      - web

volumes:
  data:
  media:
  static:
